In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("logistic_univariate.csv")
df=df[df.Padj<0.05]
df.head()

,Pattern,Feature,Coef,Std,z,P,CI_lower,CI_upper,Padj,Rank
0,Pattern_4376,cpar_Chr_2:1291351:SNP:C:T=2,3.698444,0.402544,9.187671,4.014378e-20,2.909472,4.487416,2.403850e-15,1
1,Pattern_2154,CNV_cat__CPAR2_600440=3,3.807010,0.415237,9.168287,4.805952e-20,2.993161,4.620859,2.877852e-15,2
2,Pattern_573,cpar_Chr_1:273032:SNP:C:T=2;cpar_Chr_1:273038:...,3.735254,0.411542,9.076240,1.123900e-19,2.928647,4.541862,6.730024e-15,3
3,Pattern_5811,cpar_Chr_5:656439:SNP:C:T=2,3.540908,0.391338,9.048198,1.453466e-19,2.773899,4.307918,8.703501e-15,4
4,Pattern_543,cpar_Chr_1:274924:SNP:T:C=2;cpar_Chr_1:275024:...,3.465450,0.384487,9.013175,2.001748e-19,2.711869,4.219031,1.198667e-14,5

In [4]:
len(df)

453

In [24]:
df_hr=pd.read_csv("../../Figure3/data/hr_phenotype.csv", index_col=0)[['HR']].astype(int)
df_hr.head()

         HR
Isolate
CDC335    0
CDC336    0
CDC337    0
CDC338    0
CDC339    0

In [25]:
df_pat = pd.read_csv("../../Figure4a/data/pattern_all_isolates.csv", index_col=0)
df_pat = df_pat[df.Pattern]
df_pat = pd.merge(df_pat, df_hr, left_index=True, right_index=True, how='inner')
df_pat.head()

,Pattern_4376,Pattern_2154,Pattern_573,Pattern_5811,Pattern_543,Pattern_1332,Pattern_832,Pattern_604,Pattern_4409,Pattern_395,...,Pattern_4362,Pattern_5278,Pattern_5149,Pattern_3760,Pattern_6570,Pattern_1936,Pattern_3943,Pattern_6007,Pattern_4634,HR
Isolate,,,,,,,,,,,,,,,,,,,,,
CDC335,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CDC336,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CDC337,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CDC338,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CDC339,1,1,1,1,1,1,1,1,1,1,...,1,0,1,0,0,0,0,0,0,0

In [26]:
len(df_pat)

219

In [27]:
df_pat.to_csv("Xy.csv")